### ISSUE TITLE
Tests payload is empty

### ISSUE THREAD

**Issue by Jbarget** [gitodoro/gitodoro#56]
shot.inject payload is always an empty string

**Comment by shouston3** [comment]
So it looks like you can't use shot with express. Since you are not testing an endpoint handler (like you do with vanilla node or hapi).

I've seen people using [supertest](http://willi.am/blog/2014/07/28/test-your-api-with-supertest/) for testing endpoints in express.

Tbh, it doesn't look as nice to use as shot

**Comment by shouston3** [comment]
I might just make this, I doubt it would be _that_ hard

**Comment by Jbarget** [comment]
good spot, im happy to use supertest, we havent tried it and we definitely need to be testing the payloads :)

**Comment by shouston3** [comment]
I think I've found a way around it, I think we may be able to use shot with express

**Comment by shouston3** [comment]
Yea, it's essentially two lines of code which have been hacked into shot

**Comment by shouston3** [comment]
It's not working though

**Comment by Jbarget** [comment]
or what about using supertest? (something with no hacks to get it to work with what we've got)

**Comment by shouston3** [comment]
Ok, let's use that

**Comment by shouston3** [comment]
I'm really not sure if I like to look of supertest [](https://github.com/visionmedia/supertest/issues/383).

We could just test the handlers since they are pure functions and check that they `res.send` is alled with the correct object
